name: Basic Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  rust:
    name: Rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust:
          - nightly
          - stable
          - 1.59.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy,rustfmt

    - name: Test
      run: cargo test

    - name: Format Check
      if: ${{ matrix.rust == 'nightly' && matrix.os != 'windows-latest' }}
      run: |
        cargo +nightly fmt -- --check
        cargo +nightly clippy --all-features -- --deny warnings

    - name: Run Quickcheck Tests
      if: ${{ matrix.rust == 'nightly' }}
      run: |
        cd devel
        cargo test

  doc:
    name: Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check
      run: cargo check

    - name: Docs
      run: RUSTFLAGS="-D warnings" cargo doc

    - name: Doc All Features
      run: RUSTFLAGS="-D warnings" cargo doc --all-features

  features:
    name: Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["limb32", "stdint", "limb32,stdint"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly

    - name: Check
      run: cargo check --features=limb32

    - name: Test
      run: cargo test --features=limb32

    - name: Run Quickcheck Tests
      run: |
        cd devel
        cargo  test --features=limb32
